name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Create config file
        run: |
          mkdir -p public
          echo "export const config = {
            GEMINI_API_KEY: '${{ secrets.GEMINI_API_KEY }}'
          };" > public/config.js

      - name: Copy files to public
        run: |
          cp index.html public/
          cp styles.css public/
          cp script.js public/

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: public
          token: ${{ secrets.GITHUB_TOKEN }}