name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Debug - List files
        run: |
          echo "Current directory contents:"
          ls -la
          
      - name: Create config and directories
        run: |
          mkdir -p public/images
          echo "export const config = {
            GEMINI_API_KEY: '${{ secrets.GEMINI_API_KEY }}'
          };" | tee public/config.js
          
      - name: Copy files to public
        run: |
          cp index.html public/ || echo "Failed to copy index.html"
          cp styles.css public/ || echo "Failed to copy styles.css"
          cp script.js public/ || echo "Failed to copy script.js"
          cp prompts.js public/ || echo "Failed to copy prompts.js"
          cp -r images/* public/images/ || echo "Failed to copy images"

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: public
          token: ${{ secrets.GITHUB_TOKEN }}