name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Debug - List files
        run: |
          echo "Current directory contents:"
          ls -la
          
      - name: Create config from template
        run: |
          mkdir -p public
          echo "Creating config.js with content:"
          echo "export const config = {
            GEMINI_API_KEY: '${{ secrets.GEMINI_API_KEY }}'
          };" | tee public/config.js
          
      - name: Debug - Check public directory
        run: |
          echo "Public directory contents:"
          ls -la public/

      - name: Copy files to public
        run: |
          cp index.html public/ || echo "Failed to copy index.html"
          cp styles.css public/ || echo "Failed to copy styles.css"
          cp script.js public/ || echo "Failed to copy script.js"
          cp prompts.js public/ || echo "Failed to copy prompts.js"

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: public
          token: ${{ secrets.GITHUB_TOKEN }}